version: "3"
services:
  api-server:
    build:
      context: ./../../../../ # project root
      dockerfile: ./packages/version-verifier/client/api/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.docker
    ports:
      - 8091:8091
