/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { EnsLinkV1, EnsLinkV1Interface } from "../EnsLinkV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ENS",
        name: "_ens",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "domainRegistryNode",
        type: "bytes32",
      },
    ],
    name: "getDomainOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103aa3803806103aa833981810160405281019061003291906100ed565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505061011a565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100a88261007d565b9050919050565b60006100ba8261009d565b9050919050565b6100ca816100af565b81146100d557600080fd5b50565b6000815190506100e7816100c1565b92915050565b60006020828403121561010357610102610078565b5b6000610111848285016100d8565b91505092915050565b610281806101296000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806311d4c3a214610030575b600080fd5b61004a6004803603810190610045919061013f565b610060565b60405161005791906101ad565b60405180910390f35b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166302571be3836040518263ffffffff1660e01b81526004016100bc91906101d7565b602060405180830381865afa1580156100d9573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100fd919061021e565b9050919050565b600080fd5b6000819050919050565b61011c81610109565b811461012757600080fd5b50565b60008135905061013981610113565b92915050565b60006020828403121561015557610154610104565b5b60006101638482850161012a565b91505092915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101978261016c565b9050919050565b6101a78161018c565b82525050565b60006020820190506101c2600083018461019e565b92915050565b6101d181610109565b82525050565b60006020820190506101ec60008301846101c8565b92915050565b6101fb8161018c565b811461020657600080fd5b50565b600081519050610218816101f2565b92915050565b60006020828403121561023457610233610104565b5b600061024284828501610209565b9150509291505056fea2646970667358221220d6062a5bb484524017f654d5ce9b9fc6ad6c05b63af8431bcbca904be71825b664736f6c634300080a0033";

type EnsLinkV1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EnsLinkV1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EnsLinkV1__factory extends ContractFactory {
  constructor(...args: EnsLinkV1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    _ens: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EnsLinkV1> {
    return super.deploy(_ens, overrides || {}) as Promise<EnsLinkV1>;
  }
  getDeployTransaction(
    _ens: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_ens, overrides || {});
  }
  attach(address: string): EnsLinkV1 {
    return super.attach(address) as EnsLinkV1;
  }
  connect(signer: Signer): EnsLinkV1__factory {
    return super.connect(signer) as EnsLinkV1__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EnsLinkV1Interface {
    return new utils.Interface(_abi) as EnsLinkV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EnsLinkV1 {
    return new Contract(address, _abi, signerOrProvider) as EnsLinkV1;
  }
}
