/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PackageRegistryV1Interface extends ethers.utils.Interface {
  functions: {
    "organization(bytes32)": FunctionFragment;
    "organizationController(bytes32)": FunctionFragment;
    "organizationCount()": FunctionFragment;
    "organizationExists(bytes32)": FunctionFragment;
    "organizationIds(uint256,uint256)": FunctionFragment;
    "organizationOwner(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "package(bytes32)": FunctionFragment;
    "packageController(bytes32)": FunctionFragment;
    "packageCount(bytes32)": FunctionFragment;
    "packageExists(bytes32)": FunctionFragment;
    "packageIds(bytes32,uint256,uint256)": FunctionFragment;
    "packageOwner(bytes32)": FunctionFragment;
    "registerPackage(bytes32,bytes32,address,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setOrganizationController(bytes32,address)": FunctionFragment;
    "setPackageController(bytes32,address)": FunctionFragment;
    "setPackageOwner(bytes32,address)": FunctionFragment;
    "transferOrganizationControl(bytes32,address)": FunctionFragment;
    "transferOrganizationOwnership(bytes32,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferPackageControl(bytes32,address)": FunctionFragment;
    "transferPackageOwnership(bytes32,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "organization",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "organizationController",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "organizationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "organizationExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "organizationIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "organizationOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "package", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "packageController",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "packageCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "packageExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "packageIds",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "packageOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPackage",
    values: [BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOrganizationController",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPackageController",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPackageOwner",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOrganizationControl",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOrganizationOwnership",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferPackageControl",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferPackageOwnership",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "organization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "package", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packageController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packageExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "packageIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packageOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrganizationController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPackageController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPackageOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOrganizationControl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOrganizationOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferPackageControl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferPackageOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OrganizationClaimed(bytes32,address)": EventFragment;
    "OrganizationControllerChanged(bytes32,address,address)": EventFragment;
    "OrganizationOwnerChanged(bytes32,address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PackageControllerChanged(bytes32,address,address)": EventFragment;
    "PackageOwnerChanged(bytes32,address,address)": EventFragment;
    "PackageRegistered(bytes32,bytes32,bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OrganizationClaimed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OrganizationControllerChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrganizationOwnerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PackageControllerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PackageOwnerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PackageRegistered"): EventFragment;
}

export type OrganizationClaimedEvent = TypedEvent<
  [string, string] & { organizationId: string; owner: string }
>;

export type OrganizationControllerChangedEvent = TypedEvent<
  [string, string, string] & {
    organizationId: string;
    previousController: string;
    newController: string;
  }
>;

export type OrganizationOwnerChangedEvent = TypedEvent<
  [string, string, string] & {
    organizationId: string;
    previousOwner: string;
    newOwner: string;
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type PackageControllerChangedEvent = TypedEvent<
  [string, string, string] & {
    packageId: string;
    previousController: string;
    newController: string;
  }
>;

export type PackageOwnerChangedEvent = TypedEvent<
  [string, string, string] & {
    packageId: string;
    previousOwner: string;
    newOwner: string;
  }
>;

export type PackageRegisteredEvent = TypedEvent<
  [string, string, string, string, string] & {
    organizationId: string;
    packageId: string;
    packageName: string;
    packageOwner: string;
    packageController: string;
  }
>;

export class PackageRegistryV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PackageRegistryV1Interface;

  functions: {
    organization(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, string] & {
        exists: boolean;
        owner: string;
        controller: string;
      }
    >;

    organizationController(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    organizationCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    organizationExists(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    organizationIds(
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    organizationOwner(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    package(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, string] & {
        exists: boolean;
        owner: string;
        controller: string;
      }
    >;

    packageController(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    packageCount(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    packageExists(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    packageIds(
      organizationId: BytesLike,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    packageOwner(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    registerPackage(
      organizationId: BytesLike,
      packageName: BytesLike,
      packageOwner: string,
      packageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOrganizationController(
      organizationId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPackageController(
      packageId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPackageOwner(
      packageId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOrganizationControl(
      organizationId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOrganizationOwnership(
      organizationId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferPackageControl(
      packageId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferPackageOwnership(
      packageId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  organization(
    organizationId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, string] & {
      exists: boolean;
      owner: string;
      controller: string;
    }
  >;

  organizationController(
    organizationId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  organizationCount(overrides?: CallOverrides): Promise<BigNumber>;

  organizationExists(
    organizationId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  organizationIds(
    start: BigNumberish,
    count: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  organizationOwner(
    organizationId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  package(
    packageId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, string] & {
      exists: boolean;
      owner: string;
      controller: string;
    }
  >;

  packageController(
    packageId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  packageCount(
    organizationId: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  packageExists(
    packageId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  packageIds(
    organizationId: BytesLike,
    start: BigNumberish,
    count: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  packageOwner(
    packageId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  registerPackage(
    organizationId: BytesLike,
    packageName: BytesLike,
    packageOwner: string,
    packageController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOrganizationController(
    organizationId: BytesLike,
    newController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPackageController(
    packageId: BytesLike,
    newController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPackageOwner(
    packageId: BytesLike,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOrganizationControl(
    organizationId: BytesLike,
    newController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOrganizationOwnership(
    organizationId: BytesLike,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferPackageControl(
    packageId: BytesLike,
    newController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferPackageOwnership(
    packageId: BytesLike,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    organization(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, string] & {
        exists: boolean;
        owner: string;
        controller: string;
      }
    >;

    organizationController(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    organizationCount(overrides?: CallOverrides): Promise<BigNumber>;

    organizationExists(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    organizationIds(
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    organizationOwner(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    package(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, string] & {
        exists: boolean;
        owner: string;
        controller: string;
      }
    >;

    packageController(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    packageCount(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packageExists(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    packageIds(
      organizationId: BytesLike,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    packageOwner(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    registerPackage(
      organizationId: BytesLike,
      packageName: BytesLike,
      packageOwner: string,
      packageController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setOrganizationController(
      organizationId: BytesLike,
      newController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPackageController(
      packageId: BytesLike,
      newController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPackageOwner(
      packageId: BytesLike,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOrganizationControl(
      organizationId: BytesLike,
      newController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOrganizationOwnership(
      organizationId: BytesLike,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferPackageControl(
      packageId: BytesLike,
      newController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferPackageOwnership(
      packageId: BytesLike,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OrganizationClaimed(bytes32,address)"(
      organizationId?: BytesLike | null,
      owner?: string | null
    ): TypedEventFilter<
      [string, string],
      { organizationId: string; owner: string }
    >;

    OrganizationClaimed(
      organizationId?: BytesLike | null,
      owner?: string | null
    ): TypedEventFilter<
      [string, string],
      { organizationId: string; owner: string }
    >;

    "OrganizationControllerChanged(bytes32,address,address)"(
      organizationId?: BytesLike | null,
      previousController?: string | null,
      newController?: string | null
    ): TypedEventFilter<
      [string, string, string],
      {
        organizationId: string;
        previousController: string;
        newController: string;
      }
    >;

    OrganizationControllerChanged(
      organizationId?: BytesLike | null,
      previousController?: string | null,
      newController?: string | null
    ): TypedEventFilter<
      [string, string, string],
      {
        organizationId: string;
        previousController: string;
        newController: string;
      }
    >;

    "OrganizationOwnerChanged(bytes32,address,address)"(
      organizationId?: BytesLike | null,
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { organizationId: string; previousOwner: string; newOwner: string }
    >;

    OrganizationOwnerChanged(
      organizationId?: BytesLike | null,
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { organizationId: string; previousOwner: string; newOwner: string }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "PackageControllerChanged(bytes32,address,address)"(
      packageId?: null,
      previousController?: string | null,
      newController?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { packageId: string; previousController: string; newController: string }
    >;

    PackageControllerChanged(
      packageId?: null,
      previousController?: string | null,
      newController?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { packageId: string; previousController: string; newController: string }
    >;

    "PackageOwnerChanged(bytes32,address,address)"(
      packageId?: null,
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { packageId: string; previousOwner: string; newOwner: string }
    >;

    PackageOwnerChanged(
      packageId?: null,
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { packageId: string; previousOwner: string; newOwner: string }
    >;

    "PackageRegistered(bytes32,bytes32,bytes32,address,address)"(
      organizationId?: BytesLike | null,
      packageId?: BytesLike | null,
      packageName?: BytesLike | null,
      packageOwner?: null,
      packageController?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      {
        organizationId: string;
        packageId: string;
        packageName: string;
        packageOwner: string;
        packageController: string;
      }
    >;

    PackageRegistered(
      organizationId?: BytesLike | null,
      packageId?: BytesLike | null,
      packageName?: BytesLike | null,
      packageOwner?: null,
      packageController?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      {
        organizationId: string;
        packageId: string;
        packageName: string;
        packageOwner: string;
        packageController: string;
      }
    >;
  };

  estimateGas: {
    organization(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    organizationController(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    organizationCount(overrides?: CallOverrides): Promise<BigNumber>;

    organizationExists(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    organizationIds(
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    organizationOwner(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    package(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packageController(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packageCount(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packageExists(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packageIds(
      organizationId: BytesLike,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packageOwner(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerPackage(
      organizationId: BytesLike,
      packageName: BytesLike,
      packageOwner: string,
      packageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOrganizationController(
      organizationId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPackageController(
      packageId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPackageOwner(
      packageId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOrganizationControl(
      organizationId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOrganizationOwnership(
      organizationId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferPackageControl(
      packageId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferPackageOwnership(
      packageId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    organization(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    organizationController(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    organizationCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    organizationExists(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    organizationIds(
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    organizationOwner(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    package(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    packageController(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    packageCount(
      organizationId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    packageExists(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    packageIds(
      organizationId: BytesLike,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    packageOwner(
      packageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerPackage(
      organizationId: BytesLike,
      packageName: BytesLike,
      packageOwner: string,
      packageController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOrganizationController(
      organizationId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPackageController(
      packageId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPackageOwner(
      packageId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOrganizationControl(
      organizationId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOrganizationOwnership(
      organizationId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferPackageControl(
      packageId: BytesLike,
      newController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferPackageOwnership(
      packageId: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
