/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface VerificationTreeManagerInterface extends ethers.utils.Interface {
  functions: {
    "calculateVerificationRoot()": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "onVersionVerified(bytes32,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "registry()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateRegistry(address)": FunctionFragment;
    "updateVerificationRootRelayer(address)": FunctionFragment;
    "updateVotingMachine(address)": FunctionFragment;
    "verificationRootRelayer()": FunctionFragment;
    "verifiedVersionCount()": FunctionFragment;
    "votingMachine()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateVerificationRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onVersionVerified",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerificationRootRelayer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVotingMachine",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationRootRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedVersionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingMachine",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateVerificationRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onVersionVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationRootRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVotingMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationRootRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedVersionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingMachine",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "VerificationRootCalculated(bytes32,uint256)": EventFragment;
    "VersionVerified(bytes32,bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerificationRootCalculated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VersionVerified"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type VerificationRootCalculatedEvent = TypedEvent<
  [string, BigNumber] & {
    verificationRoot: string;
    verifiedVersionCount: BigNumber;
  }
>;

export type VersionVerifiedEvent = TypedEvent<
  [string, string, BigNumber] & {
    patchNodeId: string;
    packageLocationHash: string;
    verifiedVersionIndex: BigNumber;
  }
>;

export class VerificationTreeManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VerificationTreeManagerInterface;

  functions: {
    calculateVerificationRoot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _registry: string,
      _votingMachine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onVersionVerified(
      patchNodeId: BytesLike,
      packageLocationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRegistry(
      _registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateVerificationRootRelayer(
      _verificationRootRelayer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateVotingMachine(
      _votingMachine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verificationRootRelayer(overrides?: CallOverrides): Promise<[string]>;

    verifiedVersionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    votingMachine(overrides?: CallOverrides): Promise<[string]>;
  };

  calculateVerificationRoot(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _registry: string,
    _votingMachine: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onVersionVerified(
    patchNodeId: BytesLike,
    packageLocationHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRegistry(
    _registry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateVerificationRootRelayer(
    _verificationRootRelayer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateVotingMachine(
    _votingMachine: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verificationRootRelayer(overrides?: CallOverrides): Promise<string>;

  verifiedVersionCount(overrides?: CallOverrides): Promise<BigNumber>;

  votingMachine(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    calculateVerificationRoot(overrides?: CallOverrides): Promise<string>;

    initialize(
      _registry: string,
      _votingMachine: string,
      overrides?: CallOverrides
    ): Promise<void>;

    onVersionVerified(
      patchNodeId: BytesLike,
      packageLocationHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRegistry(_registry: string, overrides?: CallOverrides): Promise<void>;

    updateVerificationRootRelayer(
      _verificationRootRelayer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateVotingMachine(
      _votingMachine: string,
      overrides?: CallOverrides
    ): Promise<void>;

    verificationRootRelayer(overrides?: CallOverrides): Promise<string>;

    verifiedVersionCount(overrides?: CallOverrides): Promise<BigNumber>;

    votingMachine(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "VerificationRootCalculated(bytes32,uint256)"(
      verificationRoot?: BytesLike | null,
      verifiedVersionCount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { verificationRoot: string; verifiedVersionCount: BigNumber }
    >;

    VerificationRootCalculated(
      verificationRoot?: BytesLike | null,
      verifiedVersionCount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { verificationRoot: string; verifiedVersionCount: BigNumber }
    >;

    "VersionVerified(bytes32,bytes32,uint256)"(
      patchNodeId?: BytesLike | null,
      packageLocationHash?: null,
      verifiedVersionIndex?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      {
        patchNodeId: string;
        packageLocationHash: string;
        verifiedVersionIndex: BigNumber;
      }
    >;

    VersionVerified(
      patchNodeId?: BytesLike | null,
      packageLocationHash?: null,
      verifiedVersionIndex?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      {
        patchNodeId: string;
        packageLocationHash: string;
        verifiedVersionIndex: BigNumber;
      }
    >;
  };

  estimateGas: {
    calculateVerificationRoot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _registry: string,
      _votingMachine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onVersionVerified(
      patchNodeId: BytesLike,
      packageLocationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRegistry(
      _registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateVerificationRootRelayer(
      _verificationRootRelayer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateVotingMachine(
      _votingMachine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verificationRootRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    verifiedVersionCount(overrides?: CallOverrides): Promise<BigNumber>;

    votingMachine(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateVerificationRoot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _registry: string,
      _votingMachine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onVersionVerified(
      patchNodeId: BytesLike,
      packageLocationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRegistry(
      _registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateVerificationRootRelayer(
      _verificationRootRelayer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateVotingMachine(
      _votingMachine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verificationRootRelayer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifiedVersionCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votingMachine(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
