/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDomainRegistryLinkV1,
  IDomainRegistryLinkV1Interface,
} from "../IDomainRegistryLinkV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "domainRegistryNode",
        type: "bytes32",
      },
    ],
    name: "getDomainOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDomainRegistryLinkV1__factory {
  static readonly abi = _abi;
  static createInterface(): IDomainRegistryLinkV1Interface {
    return new utils.Interface(_abi) as IDomainRegistryLinkV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDomainRegistryLinkV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDomainRegistryLinkV1;
  }
}
