/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IOwnershipBridgeLink,
  IOwnershipBridgeLinkInterface,
} from "../IOwnershipBridgeLink";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "domainRegistrar",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "domainRegistrarNode",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "receiveOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "domainRegistrar",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "domainRegistrarNode",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "relayOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOwnershipBridgeLink__factory {
  static readonly abi = _abi;
  static createInterface(): IOwnershipBridgeLinkInterface {
    return new utils.Interface(_abi) as IOwnershipBridgeLinkInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOwnershipBridgeLink {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IOwnershipBridgeLink;
  }
}
